### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by cedon** [mgnt/metalsmith-multimarkdown#5]
Receive the following error when attempting to install on Windows 10.0.10586:

---

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--save-dev" "metalsmith-multimarkdown"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.4
npm ERR! code ELIFECYCLE

npm ERR! mmd@4.7.1 preinstall: `make preinstall`
npm ERR! Exit status 1

---

**Comment by mgnt** [comment]
Thanks Jon - sorry, currently unable to investigate, but I think this isn't going to work on Windows because of the requirement for `make` (in the mmd project - https://github.com/mnichols/node-mmd).
